project_name: springfield
exp_name: efficientnet_b3

exp: ${exp_name}_${now_dir}

train:
  root: /home/argo/Desktop/Projects/deep_learning/kaggle/Springfield
  device: cuda

  label_to_name:
    0: abraham_grampa_simpson
    1: agnes_skinner
    2: apu_nahasapeemapetilon
    3: barney_gumble
    4: bart_simpson
    5: carl_carlson
    6: charles_montgomery_burns
    7: chief_wiggum
    8: cletus_spuckler
    9: comic_book_guy
    10: disco_stu
    11: edna_krabappel
    12: fat_tony
    13: gil
    14: groundskeeper_willie
    15: homer_simpson
    16: kent_brockman
    17: krusty_the_clown
    18: lenny_leonard
    19: lionel_hutz
    20: lisa_simpson
    21: maggie_simpson
    22: marge_simpson
    23: martin_prince
    24: mayor_quimby
    25: milhouse_van_houten
    26: miss_hoover
    27: moe_szyslak
    28: ned_flanders
    29: nelson_muntz
    30: otto_mann
    31: patty_bouvier
    32: principal_skinner
    33: professor_john_frink
    34: rainier_wolfcastle
    35: ralph_wiggum
    36: selma_bouvier
    37: sideshow_bob
    38: sideshow_mel
    39: snake_jailbird
    40: troy_mcclure
    41: waylon_smithers

  img_size: [320, 320] # (h, w)
  img_draft: False # lower quality but a lot faster to load the image

  train_split: 0.85
  val_split: 0.15 # test_split = 1 - train_split - val_split

  batch_size: 64
  epochs: 18
  use_scheduler: True
  label_smoothing: 0.1
  max_lr: 0.001
  base_lr: 0.0001
  cycler_pct_start: 0.15
  weight_decay: 0.0001

  layers_to_train: -1

  num_workers: 10
  threads_to_use: 10

  data_path: ${train.root}/data/dataset
  path_to_save: ${train.root}/output/models/${exp}
  vis_path: ${train.root}/output/visualized

  seed: 42
  cudnn_fixed: True
  debug_img_processing: False


export: # TensorRT must be done on the inference device
  half: False
  max_batch_size: 1

  model_path: ${train.path_to_save}
  path_to_data: ${train.root}/data/testset



### service ###
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

now_dir: &nowdir ${now:%Y-%m-%d}
